<Project Sdk="Tomat.Terraria.ModLoader.Sdk/2.1.0">
	<Import Project="..\tModLoader.targets" />
	
	<PropertyGroup>
		<LangVersion>preview</LangVersion>
	</PropertyGroup>
	
	<ItemGroup>
		<Reference Include="GMT">
			<HintPath>lib/GMT.dll</HintPath>
		</Reference>
		
		<Publicize Include="tModLoader;ReLogic;FNA" IncludeVirtualMembers="false" IncludeCompilerGeneratedMembers="false" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Demonstrations\" />
	  <Folder Include="lib\" />
	</ItemGroup>

</Project>